ALTER TABLE IF EXISTS item_tag DROP CONSTRAINT IF EXISTS "item_id";
ALTER TABLE IF EXISTS item DROP CONSTRAINT IF EXISTS "menu_id";
ALTER TABLE IF EXISTS tables DROP CONSTRAINT IF EXISTS "tables_store_id";

DROP TABLE IF EXISTS item_tag;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS tables;
DROP TABLE IF EXISTS stores;
