// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: food.sql

package db

import (
	"context"
)

const createMenuFood = `-- name: CreateMenuFood :one
INSERT INTO food (
	menu_id,
	name
) VALUES (
	$1, $2
) RETURNING id, menu_id, name
`

type CreateMenuFoodParams struct {
	MenuID int64  `json:"menu_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateMenuFood(ctx context.Context, arg CreateMenuFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, createMenuFood, arg.MenuID, arg.Name)
	var i Food
	err := row.Scan(&i.ID, &i.MenuID, &i.Name)
	return i, err
}

const getMenuFood = `-- name: GetMenuFood :one
SELECT id, menu_id, name FROM food
WHERE menu_id = $1 AND name = $2
`

type GetMenuFoodParams struct {
	MenuID int64  `json:"menu_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetMenuFood(ctx context.Context, arg GetMenuFoodParams) (Food, error) {
	row := q.db.QueryRowContext(ctx, getMenuFood, arg.MenuID, arg.Name)
	var i Food
	err := row.Scan(&i.ID, &i.MenuID, &i.Name)
	return i, err
}
