// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"
)

type Store struct {
	ID           int64     `json:"id"`
	StoreName    string    `json:"store_name"`
	StoreAddress string    `json:"store_address"`
	StorePhone   string    `json:"store_phone"`
	StoreOwner   string    `json:"store_owner"`
	StoreManager string    `json:"store_manager"`
	CreatedAt    time.Time `json:"created_at"`
}
