// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	CreatedAt time.Time `json:"created_at"`
}

type Item struct {
	ID     int64  `json:"id"`
	MenuID int64  `json:"menu_id"`
	Name   string `json:"name"`
	Price  int32  `json:"price"`
}

type ItemTag struct {
	ID      int64  `json:"id"`
	ItemID  int64  `json:"item_id"`
	ItemTag string `json:"item_tag"`
}

type Menu struct {
	ID        int64        `json:"id"`
	StoreID   int64        `json:"store_id"`
	MenuName  string       `json:"menu_name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Store struct {
	ID           int64     `json:"id"`
	AccountID    int64     `json:"account_id"`
	StoreName    string    `json:"store_name"`
	StoreAddress string    `json:"store_address"`
	StorePhone   string    `json:"store_phone"`
	StoreManager string    `json:"store_manager"`
	CreatedAt    time.Time `json:"created_at"`
}

type Table struct {
	ID        int64     `json:"id"`
	StoreID   int64     `json:"store_id"`
	TableID   int64     `json:"table_id"`
	TableName string    `json:"table_name"`
	CreatedAt time.Time `json:"created_at"`
}
