// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateMenuFood(ctx context.Context, arg CreateMenuFoodParams) (Food, error)
	CreateMenuFoodTag(ctx context.Context, arg CreateMenuFoodTagParams) (FoodTag, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateStoreMenu(ctx context.Context, arg CreateStoreMenuParams) (Menu, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	DeleteMenu(ctx context.Context, id int64) error
	DeleteStore(ctx context.Context, id int64) error
	DeleteStoreTable(ctx context.Context, id int64) error
	DeleteStoreTableByName(ctx context.Context, arg DeleteStoreTableByNameParams) error
	GetMenuFood(ctx context.Context, arg GetMenuFoodParams) (Food, error)
	GetMenuFoodTag(ctx context.Context, arg GetMenuFoodTagParams) (FoodTag, error)
	GetStore(ctx context.Context, id int64) (Store, error)
	GetStoreByName(ctx context.Context, storeName string) (Store, error)
	GetStoreMenu(ctx context.Context, arg GetStoreMenuParams) (Menu, error)
	GetStoreTable(ctx context.Context, arg GetStoreTableParams) (Table, error)
	ListMenuFoodTag(ctx context.Context, foodID int64) ([]string, error)
	ListStoreMenu(ctx context.Context, arg ListStoreMenuParams) ([]Menu, error)
	ListStoreTables(ctx context.Context, arg ListStoreTablesParams) ([]Table, error)
	RemoveMenuFoodTag(ctx context.Context, arg RemoveMenuFoodTagParams) error
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
	UpdateStoreMenu(ctx context.Context, arg UpdateStoreMenuParams) (Menu, error)
	UpdateStoreTable(ctx context.Context, arg UpdateStoreTableParams) error
}

var _ Querier = (*Queries)(nil)
