// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (Item, error)
	CreateMenuItemTag(ctx context.Context, arg CreateMenuItemTagParams) (ItemTag, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateStoreMenu(ctx context.Context, arg CreateStoreMenuParams) (Menu, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	DeleteMenu(ctx context.Context, id int64) error
	DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) error
	DeleteMenuItemAll(ctx context.Context, menuID int64) error
	DeleteStore(ctx context.Context, id int64) error
	DeleteStoreTable(ctx context.Context, id int64) error
	DeleteStoreTableByName(ctx context.Context, arg DeleteStoreTableByNameParams) error
	GetItem(ctx context.Context, id int64) (Item, error)
	GetMenu(ctx context.Context, id int64) (Menu, error)
	GetMenuItemTag(ctx context.Context, arg GetMenuItemTagParams) (ItemTag, error)
	GetStore(ctx context.Context, id int64) (Store, error)
	GetStoreByName(ctx context.Context, storeName string) (Store, error)
	GetStoreMenu(ctx context.Context, arg GetStoreMenuParams) (Menu, error)
	GetStoreTable(ctx context.Context, arg GetStoreTableParams) (Table, error)
	ListAllMenuItem(ctx context.Context, menuID int64) ([]Item, error)
	ListMenuItem(ctx context.Context, arg ListMenuItemParams) ([]Item, error)
	ListMenuItemTag(ctx context.Context, itemID int64) ([]string, error)
	ListStoreMenu(ctx context.Context, arg ListStoreMenuParams) ([]Menu, error)
	ListStoreTables(ctx context.Context, arg ListStoreTablesParams) ([]Table, error)
	RemoveMenuItemTag(ctx context.Context, arg RemoveMenuItemTagParams) error
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (Item, error)
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
	UpdateStoreMenu(ctx context.Context, arg UpdateStoreMenuParams) (Menu, error)
	UpdateStoreTable(ctx context.Context, arg UpdateStoreTableParams) error
}

var _ Querier = (*Queries)(nil)
