// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: tables.sql

package db

import (
	"context"
)

const createTable = `-- name: CreateTable :one
INSERT INTO tables (
    store_id,
    table_id,
    table_name
) VALUES (
    $1, $2, $3
) RETURNING id, store_id, table_id, table_name, created_at
`

type CreateTableParams struct {
	StoreID   int64  `json:"store_id"`
	TableID   int64  `json:"table_id"`
	TableName string `json:"table_name"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, createTable, arg.StoreID, arg.TableID, arg.TableName)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.TableID,
		&i.TableName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStoreTable = `-- name: DeleteStoreTable :exec
DELETE FROM tables
WHERE id = $1
`

func (q *Queries) DeleteStoreTable(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStoreTable, id)
	return err
}

const deleteStoreTableByName = `-- name: DeleteStoreTableByName :exec
DELETE FROM tables
WHERE store_id = $1 AND table_name = $2
`

type DeleteStoreTableByNameParams struct {
	StoreID   int64  `json:"store_id"`
	TableName string `json:"table_name"`
}

func (q *Queries) DeleteStoreTableByName(ctx context.Context, arg DeleteStoreTableByNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteStoreTableByName, arg.StoreID, arg.TableName)
	return err
}

const getStoreTable = `-- name: GetStoreTable :one
SELECT id, store_id, table_id, table_name, created_at FROM tables
WHERE store_id = $1 and table_id = $2
`

type GetStoreTableParams struct {
	StoreID int64 `json:"store_id"`
	TableID int64 `json:"table_id"`
}

func (q *Queries) GetStoreTable(ctx context.Context, arg GetStoreTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, getStoreTable, arg.StoreID, arg.TableID)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.TableID,
		&i.TableName,
		&i.CreatedAt,
	)
	return i, err
}

const listStoreTables = `-- name: ListStoreTables :many
SELECT id, store_id, table_id, table_name, created_at FROM tables
WHERE store_id = $1
ORDER BY table_id
LIMIT $2
OFFSET $3
`

type ListStoreTablesParams struct {
	StoreID int64 `json:"store_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListStoreTables(ctx context.Context, arg ListStoreTablesParams) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, listStoreTables, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.TableID,
			&i.TableName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreTable = `-- name: UpdateStoreTable :exec
UPDATE tables SET table_name = $3
where store_id = $1 AND table_id = $2
`

type UpdateStoreTableParams struct {
	StoreID   int64  `json:"store_id"`
	TableID   int64  `json:"table_id"`
	TableName string `json:"table_name"`
}

func (q *Queries) UpdateStoreTable(ctx context.Context, arg UpdateStoreTableParams) error {
	_, err := q.db.ExecContext(ctx, updateStoreTable, arg.StoreID, arg.TableID, arg.TableName)
	return err
}
